name: quiz
description: >
  Quiz App: Mahakarya aplikasi kuis edukatif interaktif 100% Offline. 
  Menawarkan pengalaman belajar tingkat tinggi (Premium) dengan koleksi raksasa 3.500 soal unik 
  dari 7 mata pelajaran dasar (Agama Islam, Bahasa Indonesia, Matematika, IPA, IPS, PPKn, Bahasa Inggris). 
  Dikemas dengan performa 60 FPS terkunci, mengandalkan animasi Staggered Caching, transisi rute khusus, 
  sistem suara Audio Pool multi-layer bebas hambatan, serta sistem penghargaan berbasis Gamifikasi 
  (Akurasi & Kecepatan Waktu) dengan ratusan tingkatan level untuk mencapai gelar tertinggi: Legenda!
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  lottie: ^3.1.2
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  shared_preferences: ^2.5.5
  audioplayers: ^6.6.0
  flutter_local_notifications: ^21.0.0
  timezone: ^0.11.0
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  web:
    generate: true
    image_path: "assets/images/logo.png"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/sounds/
    - assets/datasets/agamaislam/
    - assets/datasets/bahasaindonesia/
    - assets/datasets/bahasainggris/
    - assets/datasets/ilmupengetahuanalam/
    - assets/datasets/ilmupengetahuansosial/
    - assets/datasets/matematika/
    - assets/datasets/ppkn/
