// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqMVKAx9U0BDC2YZ1otFPkXKTPQWj_E34',
    appId: '1:579583447027:web:e35ddee6274abf17bd0c86',
    messagingSenderId: '579583447027',
    projectId: 'quiz-564f1',
    authDomain: 'quiz-564f1.firebaseapp.com',
    storageBucket: 'quiz-564f1.firebasestorage.app',
    measurementId: 'G-F29G7VJ4VT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBroO23P4GZPzdqQXk0tEw0B6r6Ynsdqm4',
    appId: '1:579583447027:android:89cdddb084aa35e8bd0c86',
    messagingSenderId: '579583447027',
    projectId: 'quiz-564f1',
    storageBucket: 'quiz-564f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNgMa7auWIdOFFXhNqPFR9JYE6lJvmGm0',
    appId: '1:579583447027:ios:302b9c5362a0dd41bd0c86',
    messagingSenderId: '579583447027',
    projectId: 'quiz-564f1',
    storageBucket: 'quiz-564f1.firebasestorage.app',
    iosBundleId: 'com.example.quiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqMVKAx9U0BDC2YZ1otFPkXKTPQWj_E34',
    appId: '1:579583447027:web:053f9e4f8c14ef7abd0c86',
    messagingSenderId: '579583447027',
    projectId: 'quiz-564f1',
    authDomain: 'quiz-564f1.firebaseapp.com',
    storageBucket: 'quiz-564f1.firebasestorage.app',
    measurementId: 'G-8S6922S6Y5',
  );
}
